# Shell variables
# Generated by 'wal'
wallpaper='/config/Pictures/Dunes.jpg'

# Special
background='#151c24'
foreground='#cfc6b8'
cursor='#cfc6b8'

# Colors
color0='#151c24'
color1='#505A67'
color2='#897862'
color3='#A48F6F'
color4='#BBA37A'
color5='#C3A87D'
color6='#677983'
color7='#cfc6b8'
color8='#908a80'
color9='#505A67'
color10='#897862'
color11='#A48F6F'
color12='#BBA37A'
color13='#C3A87D'
color14='#677983'
color15='#cfc6b8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
