--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/config/Pictures/Dunes.jpg"

-- Special
background="#151c24"
foreground="#cfc6b8"
cursor="#cfc6b8"

-- Colors
color0="#151c24"
color1="#505A67"
color2="#897862"
color3="#A48F6F"
color4="#BBA37A"
color5="#C3A87D"
color6="#677983"
color7="#cfc6b8"
color8="#908a80"
color9="#505A67"
color10="#897862"
color11="#A48F6F"
color12="#BBA37A"
color13="#C3A87D"
color14="#677983"
color15="#cfc6b8"
